---
- name: provision HA Kubernetes Cluster
  hosts: localhost

  tasks:
    - name: Create the KOPS S3 state store bucket
      ansible.builtin.command:
        cmd: "aws s3 mb s3://{{state_store_bucket--bucket }} --region {{ aws_region }}"
        ignore_errors: true



    - name: verify S3 bucket exists
      ansible.builtin.command:
        cmd: "kops get cluster --state=s3://{{ state_store_bucket }} --name={{ cluster_name }}"
      register: cluster_exists
      ignore_errors: true
      changed_when: false
      failed_when: false
        


    - name: Create kops cluster configuration
      ansible.builtin.command:
        cmd: >
         kops create cluster \
          --name={{ cluster_name }} \
          --state=s3://{{ state_store_bucket }}
          --zones={{ zones }} \
          --node-count={{ node_count }} \
          --node-size={{ node_size }} \
          --control-plane-size={{control_plane_size }}
          --yes
      register: cluster_create
      changed_when: 
        - "'created cluster' in cluster_create.stdout"
        - "cluster_exists.rc != 0"
      when: cluster_exists.rc != 0

